# Generated by Django 5.1 on 2024-09-24 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('ARUNACHAL PRADESH', 'ARUNACHAL PRADESH'), ('ASSAM', 'ASSAM'), ('BIHAR', 'BIHAR'), ('CHHATTISGARH', 'CHHATTISGARH'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT'), ('HARYANA', 'HARYANA'), ('HIMACHAL PRADESH', 'HIMACHAL PRADESH'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('MIZORAM', 'MIZORAM'), ('NAGALAND', 'NAGALAND'), ('ODISHA', 'ODISHA'), ('PUNJAB', 'PUNJAB'), ('RAJASTHAN', 'RAJASTHAN'), ('SIKKIM', 'SIKKIM'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('UTTARAKHAND', 'UTTARAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
