# Generated by Django 5.1 on 2024-09-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
