# Generated by Django 5.1 on 2024-09-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
